@startuml

note "Códigos de teste para fazer o papel da Api e BD" as notaGlobal

actor usuario
actor "Banco de Dados" as BD
actor API

usecase "Cadastro de usuário" as cadastro
usecase "Login de usuário" as login

usuario -- cadastro
usuario -- login
cadastro .-> login
API -left- BD : salva e resgata dados
API -- cadastro
API -- login

notaGlobal .up- BD
notaGlobal .up- API

@enduml